#!/bin/bash
# dmenu_ovpn
# Created on: Sun 28 Jun 2020 01:24:37 AM CEST
#
#  ____   __  ____  __
# (  _ \ /. |(  _ \/  )
#  )___/(_  _))___/ )(
# (__)    (_)(__)  (__)
#
# Description:
#  Script to run openvpn

notify-send "Searching for vpn files"
VPN_FILES=("tor" $(find $HOME -name "*.ovpn"))
FILE_PATH=$(echo ${VPN_FILES[*]} | tr ' ' '\n' | dmenu "$@")
pid=$(ps aux | grep "dwmstat" | head -n1 | awk -F' ' '{print $2}')

pkexec bash -c "openvpn $FILE_PATH &"
sleep 10
kill -s SIGUSR1 $pid
