#!/bin/bash
# dmenu_video
# Created on: Sun 05 Jul 2020 05:55:43 AM CEST
#
#  ____   __  ____  __
# (  _ \ /. |(  _ \/  )
#  )___/(_  _))___/ )(
# (__)    (_)(__)  (__)
#
# Description:
#  simple script to turn of the machine with dmenu

ret=$(/usr/bin/ls /dev/video* | dmenu "$@")

if [ -z "$ret" ]; then
	echo "no!"
	exit
fi

ffplay "$ret"
