#!/bin/bash
# shutdown.sh
# Created on: Sun 05 Jul 2020 05:55:43 AM CEST
#
#  ____   __  ____  __
# (  _ \ /. |(  _ \/  )
#  )___/(_  _))___/ )(
# (__)    (_)(__)  (__)
#
# Description:
#  simple script to use qemu on my machine with specific optimization for Pcores
#  and testing live machines and windows things.
#

if [ -d /home/p4p1-live ] ; then
	CONFIG_FILE=$HOME/loot/qemu/config.json
else
	CONFIG_FILE=$HOME/.qemu/config.json
fi
MANAGEMENT_SOCKET=/tmp/qemu-manage.sock

if [ ! -f $CONFIG_FILE ]; then
	[ -d /home/p4p1-live ] && mkdir $HOME/loot/qemu || mkdir -p $HOME/.qemu
	echo "{\"ram\":\"8G\",\"cores\":5,\"vm_file\":\"$HOME/.qemu/Windows.img\",\"vm_size\":\"100G\",\"virtio\":\"$HOME/.qemu/virtio-win.iso\",\"iso\":\"$HOME/.qemu/windows.iso\",\"scripts\":\"$HOME/.qemu/scripts/\"}" > $CONFIG_FILE
	qemu-img create -f qcow2 $(cat $CONFIG_FILE | jq -r .vm_file) $(cat $CONFIG_FILE | jq -r .vm_size)
fi

if [ ! -f "$(cat $CONFIG_FILE | jq -r .vm_file)" ]; then
	qemu-img create -f qcow2 $(cat $CONFIG_FILE | jq -r .vm_file) $(cat $CONFIG_FILE | jq -r .vm_size)
fi

if [ ! -f "$(cat $CONFIG_FILE | jq -r .virtio)" ]; then
	notify-send -u critical -a win "Windows Environement" "Downloading the virtio-win.iso file...." -i /etc/p3ng0s/icons/p3ng0s.png
	wget 'https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso' -o $(cat $CONFIG_FILE | jq -r .virtio)
	notify-send -u critical -a win "Windows Environement" "Done!" -i /etc/p3ng0s/icons/p3ng0s.png
fi

function settings() {
	ram=$(cat $CONFIG_FILE | jq -r .ram)
	cores=$(cat $CONFIG_FILE | jq -r .cores)
	vm_file=$(cat $CONFIG_FILE | jq -r .vm_file)
	vm_size=$(cat $CONFIG_FILE | jq -r .vm_size)
	virtio=$(cat $CONFIG_FILE | jq -r .virtio)
	zenity --forms --text "Edit Settings" --add-combo="config options" --combo-values='ram|cores|vm_file|vm_size|virtio'
}

function start_with_iso() {
	if [ ! -f $(cat $CONFIG_FILE | jq -r .virtio) ] || [ ! -f $(cat $CONFIG_FILE | jq -r .iso) ]; then
		notify-send -u critical -a win "Windows Environement" "You are missing the file $(cat $CONFIG_FILE | jq -r .virtio) file!" -i /etc/p3ng0s/icons/p3ng0s.png
		exit
	fi

	PCORES=$(for cpu in /sys/devices/system/cpu/cpu[0-9]*/topology/core_cpus_list; do
		val=$(cat "$cpu")
		echo "$val"
	done | grep '-' | tr '-' ' ' | awk '{for(i=$1;i<=$2;i++) printf i","}' | sed 's/,$//')
	PINNED=$(echo "$PCORES" | cut -d',' -f1-4)
	taskset -c "$PINNED" qemu-system-x86_64 -enable-kvm \
		-machine q35,accel=kvm \
		-object iothread,id=iothread0 \
		-drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2/x64/OVMF_CODE.4m.fd \
		-drive if=pflash,format=raw,file=/tmp/OVMF_VARS.4m.fd \
		-boot menu=on,splash-time=50000 \
		-drive id=disk0,file=$(cat $CONFIG_FILE | jq -r .vm_file),format=qcow2,if=none,cache=none,aio=io_uring \
		-device virtio-blk-pci,drive=disk0,iothread=iothread0 \
		-drive id=cdrom0,file=$(cat $CONFIG_FILE | jq -r .iso),media=cdrom,readonly=on,if=none \
		-device ide-cd,drive=cdrom0,bus=ide.0 \
		-drive id=cdrom1,file=$(cat $CONFIG_FILE | jq -r .virtio),media=cdrom,readonly=on,if=none \
		-device ide-cd,drive=cdrom1,bus=ide.1 \
		-m $(cat $CONFIG_FILE | jq -r .ram) -usb -device usb-tablet \
		-cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time -smp $(cat $CONFIG_FILE | jq -r .cores) \
		-vga std \
		-monitor unix:$MANAGEMENT_SOCKET,server,nowait \
		-netdev user,id=net0,smb=/opt/windows/ -device virtio-net-pci,netdev=net0
}

function vm_management() {
	[ ! -S $MANAGEMENT_SOCKET ] && notify-send -u critical "Error" "No VM running" && return
	ret=$(echo -e "Scripts\nScreendump\nPlugin USB\nSystem Reset\nNetwork Toggle\nSnapshots\nShutdown" | dmenu "$@")

	if echo $ret | grep "Screendump" &> /dev/null; then
		[ ! -d $HOME/Pictures/screenshots/ ] && mkdir -p $HOME/Pictures/screenshots/
		echo "screendump $HOME/Pictures/screenshots/qemu.png" | socat - unix:$MANAGEMENT_SOCKET
	elif echo $ret | grep "Scripts" &> /dev/null; then
		script_files=$(find $(cat $CONFIG_FILE | jq -r .scripts) -name "*.script")
		ret=$(echo "$script_files" | dmenu "$@")

		if [ -f $ret ]; then
			cat $ret | while read line; do
				cmd=$(echo "$line" | cut -d' ' -f1)
				arg=$(echo "$line" | cut -d' ' -f2-)

				case $cmd in
					wait) sleep "$arg" ;;
					*) echo "$line" | socat - unix-connect:/tmp/qemu-manage.sock;;
				esac
				sleep 0.4
			done
		fi
	elif echo $ret | grep "USB" &> /dev/null; then
		ret=$(lsusb | awk '{print $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16}' | dmenu "$@")
		VENDORID=$(echo "$ret" | awk '{print $1}' | cut -d":" -f1)
		PRODUCTID=$(echo "$ret" | awk '{print $1}' | cut -d":" -f2)

		echo "device_add usb-host,vendorid=0x$VENDORID,productid=0x$PRODUCTID,id=controller" | socat - unix:$MANAGEMENT_SOCKET
	elif echo $ret | grep "Reset" &> /dev/null; then
		echo "system_reset" | socat - unix:$MANAGEMENT_SOCKET
	elif echo $ret | grep "Snapshots" &> /dev/null; then
		snapshots=$(echo "info snapshots" | socat - unix:$MANAGEMENT_SOCKET | grep -E "^[0-9]+" | awk '{print $2}')
		selected=$(echo -e "New\n$snapshots" | dmenu "$@")

		if echo $selected| grep "New" &> /dev/null; then
			name=$(zenity --entry --text "Snapshot Name:")
			echo "savevm $name" | socat - unix:$MANAGEMENT_SOCKET
		else
			echo "loadvm $selected" | socat - unix:$MANAGEMENT_SOCKET
		fi
	elif echo $ret | grep "Network" &> /dev/null; then
		STATE_FILE=/tmp/qemu-net-state

		if [ -f $STATE_FILE ] && grep -q "off" $STATE_FILE; then
			echo "set_link virtio-net-pci.0 on" | socat - unix:$MANAGEMENT_SOCKET
			echo "on" > $STATE_FILE
			notify-send -a win "Windows: Network restored"
		else
			echo "set_link virtio-net-pci.0 off" | socat - unix:$MANAGEMENT_SOCKET
			echo "off" > $STATE_FILE
			notify-send -a win "Windows: Network isolated"
		fi
	elif echo $ret | grep "Shutdown" &> /dev/null; then
		echo "system_powerdown" | socat - unix-connect:$MANAGEMENT_SOCKET
	fi
}

cp /usr/share/edk2/x64/OVMF_VARS.4m.fd /tmp/OVMF_VARS.4m.fd

ret=$(echo -e " Boot Windows\n USB Boot\nﰇ Reset & Recovery\n Install to drive (iso->usb)\n Capture to VM (usb->qcow2)\n Settings\n Manage VM" | dmenu "$@")

if echo $ret | grep "Boot Windows" &> /dev/null; then
	PCORES=$(for cpu in /sys/devices/system/cpu/cpu[0-9]*/topology/core_cpus_list; do
		val=$(cat "$cpu")
		echo "$val"
	done | grep '-' | tr '-' ' ' | awk '{for(i=$1;i<=$2;i++) printf i","}' | sed 's/,$//')
	PINNED=$(echo "$PCORES" | cut -d',' -f1-4)

	taskset -c "$PINNED" qemu-system-x86_64 -enable-kvm \
		-machine q35,accel=kvm \
		-object iothread,id=iothread0 \
		-boot c \
		-drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2/x64/OVMF_CODE.4m.fd \
		-drive if=pflash,format=raw,file=/tmp/OVMF_VARS.4m.fd \
		-drive id=disk0,file=$(cat $CONFIG_FILE | jq -r .vm_file),format=qcow2,if=none,cache=none,aio=io_uring \
		-device virtio-blk-pci,drive=disk0,iothread=iothread0 \
		-drive id=cdrom1,file=$(cat $CONFIG_FILE | jq -r .virtio),media=cdrom,readonly=on,if=none \
		-device ide-cd,drive=cdrom1,bus=ide.1 \
		-m $(cat $CONFIG_FILE | jq -r .ram) -usb -device usb-tablet \
		-cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time -smp $(cat $CONFIG_FILE | jq -r .cores) \
		-vga none -device virtio-vga-gl -display sdl,gl=on \
		-monitor unix:$MANAGEMENT_SOCKET,server,nowait \
		-netdev user,id=net0,smb=/opt/windows/ -device virtio-net-pci,netdev=net0
elif echo $ret | grep "Reset" &> /dev/null; then
	start_with_iso
elif echo $ret | grep "USB Boot" &> /dev/null; then
	ret=$(lsblk -o NAME,SIZE,TYPE,MOUNTPOINT | awk '$3 == "disk" {print "/dev/"$1}' | dmenu "$@")
	PCORES=$(for cpu in /sys/devices/system/cpu/cpu[0-9]*/topology/core_cpus_list; do
		val=$(cat "$cpu")
		echo "$val"
	done | grep '-' | tr '-' ' ' | awk '{for(i=$1;i<=$2;i++) printf i","}' | sed 's/,$//')
	PINNED=$(echo "$PCORES" | cut -d',' -f1-4)

	taskset -c "$PINNED" qemu-system-x86_64 \
		-enable-kvm \
		-boot menu=on \
		-machine q35,accel=kvm \
		-cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time \
		-drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2/x64/OVMF_CODE.4m.fd \
		-drive if=pflash,format=raw,file=/tmp/OVMF_VARS.4m.fd \
		-drive file=$ret,format=raw,if=virtio,cache=none,aio=threads \
		-m $(cat $CONFIG_FILE | jq -r .ram) \
		-smp $(cat $CONFIG_FILE | jq -r .cores) \
		-vga virtio \
		-display sdl,gl=on \
		-usb \
		-monitor unix:$MANAGEMENT_SOCKET,server,nowait \
		-device usb-tablet
	# This is for Windows 11 activate it on reboot so that it doesn't connect to the internet!
#		-netdev user,id=net0,restrict=on \
#		-device virtio-net-pci,netdev=net0

elif echo $ret | grep "Install" &> /dev/null; then
	iso_path=$(zenity --file-selection --title="Select ISO" --file-filter="ISO files | *.iso")
	ret=$(lsblk -o NAME,SIZE,TYPE,MOUNTPOINT | awk '$3 == "disk" {print "/dev/"$1}' | dmenu "$@")
	PCORES=$(for cpu in /sys/devices/system/cpu/cpu[0-9]*/topology/core_cpus_list; do
		val=$(cat "$cpu")
		echo "$val"
	done | grep '-' | tr '-' ' ' | awk '{for(i=$1;i<=$2;i++) printf i","}' | sed 's/,$//')
	PINNED=$(echo "$PCORES" | cut -d',' -f1-4)

	taskset -c "$PINNED" qemu-system-x86_64 \
		-enable-kvm \
		-boot order=dc,menu=on \
		-machine q35,accel=kvm \
		-cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time \
		-drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2/x64/OVMF_CODE.4m.fd \
		-drive if=pflash,format=raw,file=/tmp/OVMF_VARS.4m.fd \
		-drive id=ssd_target,file=$ret,format=raw,if=none,cache=writeback,aio=threads \
		-device virtio-blk-pci,drive=ssd_target \
		-drive id=cdrom0,file="$iso_path",media=cdrom,readonly=on,if=none \
		-device ide-cd,drive=cdrom0,bus=ide.0 \
		-drive id=cdrom1,file=$(cat $CONFIG_FILE | jq -r .virtio),media=cdrom,readonly=on,if=none \
		-device ide-cd,drive=cdrom1,bus=ide.1 \
		-m $(cat $CONFIG_FILE | jq -r .ram) \
		-smp $(cat $CONFIG_FILE | jq -r .cores) \
		-vga virtio \
		-display sdl,gl=on \
		-usb \
		-monitor unix:$MANAGEMENT_SOCKET,server,nowait \
		-device usb-tablet
elif echo $ret | grep "Capture" &> /dev/null; then
	capture_vm_file=$(zenity --file-selection --save --title="Create qcow2 image (size of: $(cat $CONFIG_FILE | jq -r .vm_size))")
	qemu-img create -f qcow2 $capture_vm_file $(cat $CONFIG_FILE | jq -r .vm_size)

	ret=$(lsblk -o NAME,SIZE,TYPE,MOUNTPOINT | awk '$3 == "disk" {print "/dev/"$1}' | dmenu "$@")
	PCORES=$(for cpu in /sys/devices/system/cpu/cpu[0-9]*/topology/core_cpus_list; do
		val=$(cat "$cpu")
		echo "$val"
	done | grep '-' | tr '-' ' ' | awk '{for(i=$1;i<=$2;i++) printf i","}' | sed 's/,$//')
	PINNED=$(echo "$PCORES" | cut -d',' -f1-4)

	taskset -c "$PINNED" qemu-system-x86_64 \
		-enable-kvm \
		-boot order=cd,menu=on \
		-machine q35,accel=kvm \
		-cpu host,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time \
		-drive if=pflash,format=raw,readonly=on,file=/usr/share/edk2/x64/OVMF_CODE.4m.fd \
		-drive if=pflash,format=raw,file=/tmp/OVMF_VARS.4m.fd \
		-drive id=usb_source,file=$ret,format=raw,if=none,cache=none,aio=threads \
		-device usb-storage,drive=usb_source \
		-drive id=disk0,file="$capture_vm_file",format=qcow2,if=none,cache=none,aio=io_uring \
		-device virtio-blk-pci,drive=disk0 \
		-drive id=cdrom1,file=$(cat $CONFIG_FILE | jq -r .virtio),media=cdrom,readonly=on,if=none \
		-device ide-cd,drive=cdrom1,bus=ide.1 \
		-m $(cat $CONFIG_FILE | jq -r .ram) \
		-smp $(cat $CONFIG_FILE | jq -r .cores) \
		-vga virtio \
		-display sdl,gl=on \
		-usb \
		-monitor unix:$MANAGEMENT_SOCKET,server,nowait \
		-device usb-tablet
elif echo $ret | grep "Settings" &> /dev/null; then
	settings
elif echo $ret | grep "Manage" &> /dev/null; then
	vm_management "$@"
else
	echo "no!"
fi
