#!/bin/bash
# mansplain
# Created on: jeu. 04 juin 2020 06:34:08  CEST
#
#  ____   __  ____  __
# (  _ \ /. |(  _ \/  )
#  )___/(_  _))___/ )(
# (__)    (_)(__)  (__)
#
# Description:
#  Script based on luke smith's video on creating a man page dmenu list
# Dependencies:
#  sudo apt install zathura-ps zathura dmenu

man_pages=$(man -k . | sort)
ret=$(echo "$man_pages $(/usr/bin/ls /etc/p3ng0s/docs/)" | dmenu "$@" | cut -d' ' -f1)
if [ ! -z $ret ]; then
	if echo $ret | grep "p3ng0s-" &> /dev/null; then
		zathura /etc/p3ng0s/docs/$ret
	else
		man -Tps $ret | zathura -
	fi
fi

exit
